### ISSUE TITLE
Can I use Gfortran with Abaqus on Windows?/Windows环境下能否在Abaqus中使用Gfortran？

### ISSUE THREAD

**Issue by Clayblockunova** [Yazhuo-Liu/install-abaqus-with-fortran-on-windows#1]
Hello!
With tools like MSYS2, Gfortran can be installed on Windows. Can I use Gfortran with Abaqus on Windows? What should I do for binding?
您好！
使用MSYS2或类似工具可以在Windows中安装Gfortran。请问Windows环境下能否在Abaqus中使用Gfortran？需要如何绑定？

**Comment by Yazhuo-Liu** [comment]
Abaqus does not seem to include gfortran in its official support, so the connection method for gfortran is not given. Referring to the connection method of ifort, it may be necessary to modify the abaqus_v6.env file so that abaqus can recognize the gfortran compiler.

According to [@mwierszycki](https://github.com/mwierszycki/gfortran_for_abaqus/tree/main), the example config file is:
`import os
abaHomeInc = os.path.abspath(os.path.join(os.environ.get('ABA_HOME', ''), os.pardir))
fortCmd = "gfortran"
compile_fortran = [fortCmd, '-c', '-cpp', '-fPIC', '-extend-source', '-DABQ_LNX86_64', '-DABQ_FORTRAN', '-fautomatic', '-mno-fma', '-fprotect-parens', '-fstack-protector-strong', '-msse3', '-mavx', '-mavx2', '-ffixed-line-length-none', '-I%I', '-I'+abaHomeInc, '%P']
link_sl = [fortCmd, '-fPIC', '-shared', '-Wl,--add-needed', '%E', '-Wl,-soname,%U', '-o', '%U', '%F', '%A', '%L', '%B', '-Wl,-Bdynamic']
link_exe = [fortCmd, '-fPIC', '-Wl,-Bdynamic', '-Wl,--add-needed', '-o', '%J', '%F', '%M', '%L', '%B', '%O']
del fortCmd
del abaHomeInc
`
You may still need to find the environment variables you need to change
